services:
  database:
    image: postgres
    healthcheck:
      test: pg_isready
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:?please set database password}"
      POSTGRES_DB: 'boenergotask'
      POSTGRES_USER: 'django'
    volumes:
      - db-data-boenergotask:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        - PORT=8000
    environment:
      DJANGO_DEBUG: "${DJANGO_DEBUG:-False}"
      DB_HOST: database
      DB_PASSWORD:
      LOG_LEVEL: debug
    volumes:
      - uploads-boenergotask:/usr/src/images/uploads/
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    environment:
      VIRTUAL_HOST:
      LETSENCRYPT_HOST:
    depends_on:
      - web
    networks:
      - nginx-proxy
      - default

volumes:
  uploads-boenergotask:
    name: "uploads-boenergotask"
  db-data-boenergotask:
    name: "boenergotask-db"

networks:
  default:
  nginx-proxy:
    external: true
