# Generated by Django 3.2.13 on 2022-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('roots_num', models.PositiveIntegerField()),
                ('root_1', models.FloatField(null=True)),
                ('root_2', models.FloatField(null=True)),
            ],
        ),
    ]
