# Generated by Django 3.2.13 on 2022-06-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hundreditems', '0002_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='max_items',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
